// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANMAloYVFZpcbspGU9U2c5lZIKjCS-KVc',
    appId: '1:481297222762:web:cf9784f5f95b2d9d6e0e13',
    messagingSenderId: '481297222762',
    projectId: 'phone-auth-a667b',
    authDomain: 'phone-auth-a667b.firebaseapp.com',
    storageBucket: 'phone-auth-a667b.appspot.com',
    measurementId: 'G-GN0QKV3F1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIR7AO0EqXJXcdROHUm2bUjRHmGcEPaHs',
    appId: '1:481297222762:android:e580ec8cc65a5b9a6e0e13',
    messagingSenderId: '481297222762',
    projectId: 'phone-auth-a667b',
    storageBucket: 'phone-auth-a667b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-0yIQhk6p-94271-9GYfNBRsPRomPf88',
    appId: '1:481297222762:ios:74c0739c8770f5506e0e13',
    messagingSenderId: '481297222762',
    projectId: 'phone-auth-a667b',
    storageBucket: 'phone-auth-a667b.appspot.com',
    iosBundleId: 'com.example.otpAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-0yIQhk6p-94271-9GYfNBRsPRomPf88',
    appId: '1:481297222762:ios:1e6d38e14e6174e46e0e13',
    messagingSenderId: '481297222762',
    projectId: 'phone-auth-a667b',
    storageBucket: 'phone-auth-a667b.appspot.com',
    iosBundleId: 'com.example.otpAuth.RunnerTests',
  );
}
